# Generated by Django 3.0.3 on 2020-03-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200325_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19_tb',
            name='active',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='covid19_tb',
            name='critical',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='covid19_tb',
            name='recovered',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='covid19_tb',
            name='today_cases',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='covid19_tb',
            name='today_deaths',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='covid19_tb',
            name='total_cases',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='covid19_tb',
            name='total_deaths',
            field=models.IntegerField(max_length=30),
        ),
    ]
