# Generated by Django 3.0.4 on 2020-03-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200325_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_covid',
            fields=[
                ('all_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cases', models.IntegerField(max_length=30)),
                ('Deaths', models.IntegerField(max_length=30)),
                ('Recovered', models.IntegerField(max_length=30)),
            ],
        ),
    ]
