# Generated by Django 3.0.4 on 2020-03-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_all_covid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_covid',
            old_name='Cases',
            new_name='Cases_all',
        ),
    ]
